Feature
elfin-git/My-portfolio pull request #1
Opened 2022-05-26 17:50 UTC by elfin-git

I managed to set up the first page of the mobile portfolio

2022-05-26 20:16 UTC, Mre55 requested changes
**Hi @elfin-git,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 10:36 UTC, ishimwezachee requested changes
Hi @elfin-git  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-05-27 10:36 UTC, ishimwezachee commented on index.html
> +   </div>
- [ ] As Previous mentioned, you should you semantic elements in the right way.  You don't need to put some elements outside the sementic elements, I guess this example will help you 
![image](https://user-images.githubusercontent.com/43877689/170682039-08604494-0405-4a96-a227-a22cde2009a7.png)

2022-05-27 10:36 UTC, ishimwezachee commented on index.html
> +  <a href=""><p class="work">&#8595; Work</p></a>
- [ OPTIONAL] I am sorry, the previous reviewer forgot to mention this, but  Your Icons should be in `ul `tag to group them, and `li `per icon and each icon should have a link(tag). This is a good HTML practice and it will make you codes more clean

2022-05-27 11:33 UTC, elfin-git commented on index.html
> +   </div>
@ishimwezachee I don't understand what you mean on the semantic elements part

2022-05-27 13:15 UTC, vechicin requested changes
# Hi @elfin-git  ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good commit history
- [x] Correct GitHub Flow
- [x] Good job following some of the previous reviewers' changes

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 13:15 UTC, vechicin commented on index.html
> +      </h5>
According to the evaluation guidelines, this content should be wrapped inside a `<p>` tag. Kindly fix this.

<img width="338" alt="Screen Shot 2022-05-27 at 8 00 43" src="https://user-images.githubusercontent.com/82426682/170704198-a09bb5ce-a251-4d7b-ad34-5c0e78ac04b9.png">

2022-05-27 13:15 UTC, vechicin commented on index.html
> + </div>
According to the evaluation guidelines, this section should be wrapped inside a `<ul>` tag and each icon should be wrapped inside a `<li>` tag. Additionally, each icon needs to have a link tag as well. Kindly fix this.

<img width="604" alt="Screen Shot 2022-05-27 at 8 02 48" src="https://user-images.githubusercontent.com/82426682/170704503-84eca577-afd7-402d-bc49-41a7538a5536.png">

2022-05-27 13:15 UTC, vechicin commented on styles.css
> +}
Your design is still not quite close enough to the template design.

Here's your design:

<img width="245" alt="Screen Shot 2022-05-27 at 8 05 33" src="https://user-images.githubusercontent.com/82426682/170704937-5269bbaa-c503-405e-b17c-f757ade19abb.png">

Here's the template design:

<img width="266" alt="Screen Shot 2022-05-27 at 8 05 51" src="https://user-images.githubusercontent.com/82426682/170704997-c048c456-6a7b-4abb-b79e-cc5ac9ad4799.png">

Do you see how different the text size and the size of the hamburger are? The margins or padding you are using need to be fixed as well. Kindly fix this.

2022-05-27 13:15 UTC, vechicin commented on styles.css
> +}
This section needs to follow the template design closer as well.

Take a look at your design:

<img width="244" alt="Screen Shot 2022-05-27 at 8 08 18" src="https://user-images.githubusercontent.com/82426682/170705383-711ea7f9-6e6c-4904-8615-5bcd0ced6d51.png">

Take a look at the template design:

<img width="268" alt="Screen Shot 2022-05-27 at 8 08 44" src="https://user-images.githubusercontent.com/82426682/170705459-8e09b219-42a0-4bcd-a8cf-c1e8999f7768.png">

Do you see how much space there is between one technology and the item below? Kindly fix this.

2022-05-27 13:15 UTC, vechicin commented on README.md
> +N/A
[OPTIONAL] I recommend you remove this section until you deploy a live demo. It makes your documentation look a little unnprofessional.

2022-05-27 13:15 UTC, vechicin commented on README.md
>  ## Getting Started
[OPTIONAL] I recommend you add instructions on how to get a local copy of this project and how to install the necessary dependencies for it to run properly. This might not seem important at the moment, but later on, with more complex projects, this will be a requirement so it is better to get in the habit of doing so from early on.

2022-05-27 13:15 UTC, vechicin commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/tracy_muso)
[OPTIONAL] I recommend changing the default handles to your GitHub and Twitter handles.

If you have a LinkedIn profile already, I recommend you add it to your documentation, this will be the first thing recruiters will look for if they are interested in your project and want to get in touch with you.

2022-05-30 14:37 UTC, sja-thedude commented on index.html
> +    </header>
Implemented 👍

2022-05-30 14:37 UTC, sja-thedude commented on index.html
> +   </div>
Implemented 👍

2022-05-30 14:37 UTC, sja-thedude commented on index.html
> +      </h5>
Implemented 👍

2022-05-30 14:38 UTC, sja-thedude commented on index.html
> + </div>
Implemented 👍

2022-05-30 14:41 UTC, sja-thedude commented on styles.css
> +}
Implemented 👍

2022-05-30 14:52 UTC, elfin-git commented on index.html
> + </div>
@sja-thedude Are there any changes needed to be done?

2022-05-30 14:58 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @elfin-git, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️Good job so far

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 14:58 UTC, sja-thedude commented on index.html
> +       <hr class="line2">
- [ ] As suggested by the previous reviewer [here](https://github.com/elfin-git/My-portfolio/pull/1#discussion_r883599597), Kindly make sure you place frameworks in place of skills and vice versa as per the original design as shown below.

_Your design is on the right and original on the left_

![2022-05-30 (2)](https://user-images.githubusercontent.com/70269507/171017151-57760a2d-c68b-479f-b37b-91493f0505b1.png)

2022-05-30 15:16 UTC, elfin-git commented on index.html
> +       <hr class="line2">
@sja-thedude I have corrected the order of languages, frameworks and skills.

2022-05-30 15:25 UTC, ShadyShawkat approved these changes
## Hi @elfin-git, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 15:31 UTC, merged