Desktop version media queries
elfin-git/My-portfolio pull request #4
Opened 2022-06-08 19:17 UTC by elfin-git

I made some additions to the Html to suit the desktop version and I also added media queries for the desktop version.

2022-06-08 20:32 UTC, youmari requested changes
Hi @elfin-git , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary 
✔️ No linter error
✔️ Great commit messages

## Required Changes ♻️

- [ ] on the mobile version above the my recent section you should only have one divider and it should be the same as the Figma design please try to fix that 
- Figma 
![image](https://user-images.githubusercontent.com/61790587/172710584-3a3f5c79-a9ca-472b-b13d-29bc2392cc74.png)
- Yours 
![image](https://user-images.githubusercontent.com/61790587/172710652-209a273c-4e40-4b97-80cc-5ef75a9354ce.png)

- [ ] please try to use the right font family in the titles of the section please you should use 
![image](https://user-images.githubusercontent.com/61790587/172710894-f4dfed05-5faa-4515-9580-5343f8d7cbb1.png)

- [ ] please try to add the right font family to the all button and also the right effect on hover and pressed, the button should be the same as in the Figma design 
![image](https://user-images.githubusercontent.com/61790587/172711141-6a9c1a3d-a562-4436-8805-958b2450b158.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 20:32 UTC, youmari commented on index.html
> +         <li class="page">Contact</li>
- [ ] these are navigations links so please try to cover them with an `<a>` tag in order to be clickable

2022-06-08 20:32 UTC, youmari commented on index.html
>         <p class="mps">A daily selection of privately personalized reads;
- [ ] Your Portfolio should be responsive on all devices right now but on 800px wide screen your projects cards have an overflow with text and project image please make sure to fix that 
![image](https://user-images.githubusercontent.com/61790587/172709932-4d04d826-281b-4d40-bf47-3142cab79926.png)

2022-06-08 20:32 UTC, youmari commented on index.html
> +       <button class="button" type="submit">Send</button>
- [ ] please make sure this button is not displayed on the mobile version 
![image](https://user-images.githubusercontent.com/61790587/172711340-ba382466-59a4-421f-90c0-18d6f01f7784.png)

2022-06-08 20:32 UTC, youmari commented on index.html
>         <button class="btn" type="submit">See project</button>
- [ ] it would be better to add some padding to your inputs in order to match the ones in the Figma design so please try to do that 
- Figma
![image](https://user-images.githubusercontent.com/61790587/172711538-5c9b59bc-6ea8-4201-afe1-0f886753d22b.png)
- Yours 
![image](https://user-images.githubusercontent.com/61790587/172711562-36f467d8-e246-44a5-87ef-ddd3abbd46be.png)

2022-06-09 11:27 UTC, elfin-git commented
The default font for the whole website is Roboto, I was adding a different font to the elements that required it. It will look different according to the generic family I use. It is impossible to make the exact replica of the figma desktop version on all screens ranging from 768px wide. I did do my best to make sure the design made sense on the possible big screen sizes.

2022-06-09 11:42 UTC, muneebulrehman requested changes
Hi @elfin-git , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good commit messages.
- Good follow-up with the previous reviewer.


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly implement the button interaction as asked by the previous reviewer.
![image](https://user-images.githubusercontent.com/33268927/172838565-d8650954-e37d-4dc8-9276-f944516ba968.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 11:42 UTC, muneebulrehman commented on index.html
> +       <button class="button" type="submit">Send</button>
@elfin-git , your send is button is gone, and the `see project` button is still there. Kindly fix it. 
Here is the snapshot of your application.
![image](https://user-images.githubusercontent.com/33268927/172837759-cfb8feb6-346c-4926-ab53-e7161d533303.png)

2022-06-09 11:42 UTC, muneebulrehman commented on index.html
>         <button class="btn" type="submit">See project</button>
Kindly add the padding as requested by the previous reviewer.

2022-06-09 13:59 UTC, merged